version: '3'
services:
  postgres:
    container_name: pokemondb
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env.docker

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8080:80
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env.docker
